import type { Metadata } from "next";
import "./globals.css";
import AppContainer from "@/components/app-container";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-gray-100">
        <AppContainer>
          <SessionProvider>{children}</SessionProvider>
        </AppContainer>
      </body>
    </html>
  );
}
